### ISSUE TITLE
Hello, I would like to give you an idea for this wonderful application! You could put the option to log into the google drive account and the One Drive account and make the backups directly on the cloud! That would be great, and the app icon could be in the System Settings App instead of the app menu. Thank you! I am very happy for the new apps, this makes Elementary OS even better.

### ISSUE THREAD

**Issue by 20alice2emanueli** [chasinglogic/tardis#30] opened 2020-02-24 20:18 UTC

**Comment by chasinglogic** [comment] 2020-02-24 21:16
Closing as a dupe of #31

**Closed by chasinglogic** 2020-02-24 21:16 UTC
